/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Path308Image from 'src/assets/images/Activity_Path_308.png';
import Path194Image from 'src/assets/images/Activity_Path_194.png';
import Path195Image from 'src/assets/images/Activity_Path_195.png';
import Path196Image from 'src/assets/images/Activity_Path_196.png';
import Path197Image from 'src/assets/images/Activity_Path_197.png';
import Path198Image from 'src/assets/images/Activity_Path_198.png';
import Path199Image from 'src/assets/images/Activity_Path_199.png';
import Path200Image from 'src/assets/images/Activity_Path_200.png';
import Path201Image from 'src/assets/images/Activity_Path_201.png';
import Path202Image from 'src/assets/images/Activity_Path_202.png';
import Path203Image from 'src/assets/images/Activity_Path_203.png';
import Path204Image from 'src/assets/images/Activity_Path_204.png';
import Path205Image from 'src/assets/images/Activity_Path_205.png';
import Path206Image from 'src/assets/images/Activity_Path_206.png';
import { styled } from '@mui/material/styles';
import { ActivityProps } from 'src/types';

const Activity1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: `453.22px`,
  height: `191px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const TopandBottomFrame: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  width: `429.22px`,
  left: `12px`,
  top: `0px`,
});

const TopFrame: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const UsernameFrame: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Username: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(6, 5, 6, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `27px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `59px`,
  textTransform: `none`,
  margin: `0px`,
});

const ActivityDateFrame: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const ActivityDate: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(126, 126, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `39px`,
  textTransform: `none`,
  margin: `0px`,
});

const BottomFrame: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `15px 0px 0px 0px`,
});

const AvatarFrame: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const VrdellaAvatar: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `70.94px`,
  width: `73.22px`,
  margin: `0px`,
});

const Path308: any = styled('img')({
  height: `70.94px`,
  width: `73.22px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group12: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `41.47px`,
  height: `51.34px`,
  left: `16px`,
  top: `8px`,
});

const Group11: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `41.47px`,
  height: `51.34px`,
  left: `0px`,
  top: `0px`,
});

const Group10: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `41.47px`,
  height: `51.06px`,
  left: `0px`,
  top: `0px`,
});

const Path194: any = styled('img')({
  height: `20.68px`,
  width: `41.47px`,
  position: `absolute`,
  left: `0px`,
  top: `30px`,
});

const Path195: any = styled('img')({
  height: `20.68px`,
  width: `20.74px`,
  position: `absolute`,
  left: `21px`,
  top: `30px`,
});

const Rectangle31: any = styled('div')({
  backgroundColor: `rgba(241, 201, 165, 1)`,
  width: `8.26px`,
  height: `13.39px`,
  position: `absolute`,
  left: `17px`,
  top: `22px`,
});

const Rectangle32: any = styled('div')({
  backgroundColor: `rgba(228, 182, 146, 1)`,
  width: `4.13px`,
  height: `13.39px`,
  position: `absolute`,
  left: `21px`,
  top: `22px`,
});

const Path196: any = styled('img')({
  height: `9.46px`,
  width: `8.26px`,
  position: `absolute`,
  left: `17px`,
  top: `22px`,
});

const Path197: any = styled('img')({
  height: `28.27px`,
  width: `21.24px`,
  position: `absolute`,
  left: `10px`,
  top: `0px`,
});

const Path198: any = styled('img')({
  height: `8.3px`,
  width: `7.07px`,
  position: `absolute`,
  left: `27px`,
  top: `11px`,
});

const Path199: any = styled('img')({
  height: `8.3px`,
  width: `7.07px`,
  position: `absolute`,
  left: `8px`,
  top: `11px`,
});

const Path200: any = styled('img')({
  height: `28.27px`,
  width: `10.62px`,
  position: `absolute`,
  left: `21px`,
  top: `0px`,
});

const Path201: any = styled('img')({
  height: `19.35px`,
  width: `41.47px`,
  position: `absolute`,
  left: `0px`,
  top: `32px`,
});

const Path202: any = styled('img')({
  height: `17.42px`,
  width: `17.41px`,
  position: `absolute`,
  left: `9px`,
  top: `0px`,
});

const Path203: any = styled('img')({
  height: `14.37px`,
  width: `6.61px`,
  position: `absolute`,
  left: `26px`,
  top: `2px`,
});

const Path204: any = styled('img')({
  height: `8.27px`,
  width: `7.59px`,
  position: `absolute`,
  left: `21px`,
  top: `32px`,
});

const Path205: any = styled('img')({
  height: `14.34px`,
  width: `1.62px`,
  position: `absolute`,
  left: `19px`,
  top: `37px`,
});

const Path206: any = styled('img')({
  height: `8.27px`,
  width: `7.59px`,
  position: `absolute`,
  left: `13px`,
  top: `32px`,
});

const StatusFrame: any = styled('div', {
  shouldForwardProp: (prop: any) => !['props'].includes(prop.toString()),
})(({ props }: any) => ({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  borderRadius: `9px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `4px 18px`,
  margin: `0px 0px 0px 241px`,
  backgroundColor: props.activity.backgroundColor,
}));

const VrdellaStatus: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `28px`,
  textTransform: `none`,
  margin: `0px`,
});

function Activity(props: ActivityProps): JSX.Element {
  return (
    <Activity1>
      <TopandBottomFrame>
        <TopFrame>
          <UsernameFrame>
            <Username>{props.activity.name}</Username>
          </UsernameFrame>
          <ActivityDateFrame>
            <ActivityDate>{props.activity.activityDate}</ActivityDate>
          </ActivityDateFrame>
        </TopFrame>
        <BottomFrame>
          <AvatarFrame>
            <VrdellaAvatar>
              <Path308 src={Path308Image} loading="lazy" alt={'Path 308'} />
              <Group12>
                <Group11>
                  <Group10>
                    <Path194
                      src={Path194Image}
                      loading="lazy"
                      alt={'Path 194'}
                    />
                    <Path195
                      src={Path195Image}
                      loading="lazy"
                      alt={'Path 195'}
                    />
                    <Rectangle31></Rectangle31>
                    <Rectangle32></Rectangle32>
                    <Path196
                      src={Path196Image}
                      loading="lazy"
                      alt={'Path 196'}
                    />
                    <Path197
                      src={Path197Image}
                      loading="lazy"
                      alt={'Path 197'}
                    />
                    <Path198
                      src={Path198Image}
                      loading="lazy"
                      alt={'Path 198'}
                    />
                    <Path199
                      src={Path199Image}
                      loading="lazy"
                      alt={'Path 199'}
                    />
                    <Path200
                      src={Path200Image}
                      loading="lazy"
                      alt={'Path 200'}
                    />
                  </Group10>
                  <Path201 src={Path201Image} loading="lazy" alt={'Path 201'} />
                  <Path202 src={Path202Image} loading="lazy" alt={'Path 202'} />
                  <Path203 src={Path203Image} loading="lazy" alt={'Path 203'} />
                  <Path204 src={Path204Image} loading="lazy" alt={'Path 204'} />
                  <Path205 src={Path205Image} loading="lazy" alt={'Path 205'} />
                  <Path206 src={Path206Image} loading="lazy" alt={'Path 206'} />
                </Group11>
              </Group12>
            </VrdellaAvatar>
          </AvatarFrame>
          <StatusFrame props={props}>
            <VrdellaStatus>{props.activity.status}</VrdellaStatus>
          </StatusFrame>
        </BottomFrame>
      </TopandBottomFrame>
    </Activity1>
  );
}

export default Activity;
