/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import AdobeStock3702221581Image from 'src/assets/images/virtusigsignin_AdobeStock_370222158_1.png';
import VirtusigLogo2Image from 'src/assets/images/virtusigsignin_Virtusig_logo_2.png';
import { styled } from '@mui/material/styles';
import { VirtusigSigninProps } from 'src/types';
import useVirtusigSignin from 'src/components/VirtusigSignin/useVirtusigSignin';

const VirtusigSignin1: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: `1920px`,
  height: `1024px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const AdobeStock3702221581: any = styled('img')({
  height: `1024px`,
  width: `977px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `944px`,
  top: `3px`,
});

const Rectangle593: any = styled('div')({
  backgroundColor: `rgba(246, 247, 248, 1)`,
  width: `910px`,
  height: `914px`,
  position: `absolute`,
  left: `16px`,
  top: `40px`,
});

const Rectangle592: any = styled('div')({
  background: `linear-gradient(-179.91deg, rgba(92, 62, 133, 1) 60.96433129502309%, rgba(98, 73, 131, 0) 191.344261594868%)`,
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `944px`,
  height: `1024px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const VirtusigLogo2: any = styled('img')({
  height: `262px`,
  width: `248px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `347px`,
  top: `65px`,
});

const Group160: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `208px`,
  height: `74px`,
  left: `389px`,
  top: `791px`,
});

const Rectangle447: any = styled('div')({
  backgroundColor: `rgba(172, 158, 191, 1)`,
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  borderRadius: `9px`,
  width: `208px`,
  height: `67px`,
  position: `absolute`,
  left: `0px`,
  top: `2px`,
});

const Send: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(250, 250, 250, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `74px`,
  textTransform: `none`,
  position: `absolute`,
  left: `59px`,
  top: `0px`,
});

const DateSignedField: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(115, 235, 252, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `800`,
  fontSize: `38px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `63px`,
  textTransform: `none`,
  position: `absolute`,
  left: `88px`,
  top: `363px`,
});

const DateSignedField1: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(235, 235, 235, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `38px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `63px`,
  textTransform: `none`,
  position: `absolute`,
  left: `88px`,
  top: `515px`,
});

const DateSignedField2: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(235, 235, 235, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `38px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `63px`,
  textTransform: `none`,
  position: `absolute`,
  left: `88px`,
  top: `659px`,
});

const Line81: any = styled('div')({
  border: `3px solid rgba(255, 255, 255, 1)`,
  width: `542px`,
  height: `0px`,
  position: `absolute`,
  left: `291px`,
  top: `571px`,
});

const Line82: any = styled('div')({
  border: `3px solid rgba(255, 255, 255, 1)`,
  width: `542px`,
  height: `0px`,
  position: `absolute`,
  left: `291px`,
  top: `713px`,
});

const Send1: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `74px`,
  textTransform: `none`,
  position: `absolute`,
  left: `259px`,
  top: `872px`,
});

const Rectangle595: any = styled('div')({
  width: `441px`,
  height: `515px`,
  position: `absolute`,
  left: `943px`,
  top: `0px`,
});

const Rectangle596: any = styled('div')({
  backgroundColor: `rgba(93, 62, 133, 0.3)`,
  width: `976px`,
  height: `1024px`,
  position: `absolute`,
  left: `944px`,
  top: `0px`,
});

function VirtusigSignin(props: VirtusigSigninProps): JSX.Element {
  const { fns } = useVirtusigSignin();

  return (
    <VirtusigSignin1>
      <AdobeStock3702221581
        src={AdobeStock3702221581Image}
        loading="lazy"
        alt={'AdobeStock_370222158 1'}
      />
      <Rectangle593></Rectangle593>
      <Rectangle592></Rectangle592>
      <VirtusigLogo2
        src={VirtusigLogo2Image}
        loading="lazy"
        alt={'Virtusig logo 2'}
      />
      <Group160>
        <Rectangle447></Rectangle447>
        <Send>{`Submit`}</Send>
      </Group160>
      <DateSignedField>{`Login`}</DateSignedField>
      <DateSignedField1>{fns.getButtonText()}</DateSignedField1>
      <DateSignedField2>{`Password`}</DateSignedField2>
      <Line81 onMouseEnter={fns.username()}></Line81>
      <Line82></Line82>
      <Send1>{`Forgot Password? or Signin as a different User`}</Send1>
      <Rectangle595></Rectangle595>
      <Rectangle596></Rectangle596>
    </VirtusigSignin1>
  );
}

export default VirtusigSignin;
