/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

const useVirtusigDashboard = () => {
  let data: any = {};
  const getWaitingForOthers = (): any => {};
  const getCompleted = (): any => {};
  const getCompletedColor = (): any => {};
  const getExpired = (): any => {};
  const getExpiredColor = (): any => {};
  const getBackgroundClip = (): any => {};

  let fns: any = {
    getWaitingForOthers,
    getCompleted,
    getCompletedColor,
    getExpired,
    getExpiredColor,
    getBackgroundClip,
  };
  return { data, fns };
};

export default useVirtusigDashboard;
