/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import VirtusigLogo2Image from 'src/assets/images/VirtusigDashboard_Virtusig_logo_2.png';
import Path556Image from 'src/assets/images/VirtusigDashboard_Path_556.png';
import Path557Image from 'src/assets/images/VirtusigDashboard_Path_557.png';
import Path558Image from 'src/assets/images/VirtusigDashboard_Path_558.png';
import Path559Image from 'src/assets/images/VirtusigDashboard_Path_559.png';
import Path560Image from 'src/assets/images/VirtusigDashboard_Path_560.png';
import Path308Image from 'src/assets/images/VirtusigDashboard_Path_308_3.png';
import Path194Image from 'src/assets/images/VirtusigDashboard_Path_194_3.png';
import Path195Image from 'src/assets/images/VirtusigDashboard_Path_195_3.png';
import Path196Image from 'src/assets/images/VirtusigDashboard_Path_196_3.png';
import Path197Image from 'src/assets/images/VirtusigDashboard_Path_197_3.png';
import Path198Image from 'src/assets/images/VirtusigDashboard_Path_198_3.png';
import Path199Image from 'src/assets/images/VirtusigDashboard_Path_199_3.png';
import Path200Image from 'src/assets/images/VirtusigDashboard_Path_200_3.png';
import Path201Image from 'src/assets/images/VirtusigDashboard_Path_201_3.png';
import Path202Image from 'src/assets/images/VirtusigDashboard_Path_202_3.png';
import Path203Image from 'src/assets/images/VirtusigDashboard_Path_203_3.png';
import Path204Image from 'src/assets/images/VirtusigDashboard_Path_204_3.png';
import Path205Image from 'src/assets/images/VirtusigDashboard_Path_205_3.png';
import Path206Image from 'src/assets/images/VirtusigDashboard_Path_206_3.png';
import Path3081Image from 'src/assets/images/VirtusigDashboard_Path_308_2.png';
import Path1941Image from 'src/assets/images/VirtusigDashboard_Path_194_2.png';
import Path1951Image from 'src/assets/images/VirtusigDashboard_Path_195_2.png';
import Path1961Image from 'src/assets/images/VirtusigDashboard_Path_196_2.png';
import Path1971Image from 'src/assets/images/VirtusigDashboard_Path_197_2.png';
import Path1981Image from 'src/assets/images/VirtusigDashboard_Path_198_2.png';
import Path1991Image from 'src/assets/images/VirtusigDashboard_Path_199_2.png';
import Path2001Image from 'src/assets/images/VirtusigDashboard_Path_200_2.png';
import Path2011Image from 'src/assets/images/VirtusigDashboard_Path_201_2.png';
import Path2021Image from 'src/assets/images/VirtusigDashboard_Path_202_2.png';
import Path2031Image from 'src/assets/images/VirtusigDashboard_Path_203_2.png';
import Path2041Image from 'src/assets/images/VirtusigDashboard_Path_204_2.png';
import Path2051Image from 'src/assets/images/VirtusigDashboard_Path_205_2.png';
import Path2061Image from 'src/assets/images/VirtusigDashboard_Path_206_2.png';
import Path3082Image from 'src/assets/images/VirtusigDashboard_Path_308_1.png';
import Path1942Image from 'src/assets/images/VirtusigDashboard_Path_194_1.png';
import Path1952Image from 'src/assets/images/VirtusigDashboard_Path_195_1.png';
import Path1962Image from 'src/assets/images/VirtusigDashboard_Path_196_1.png';
import Path1972Image from 'src/assets/images/VirtusigDashboard_Path_197_1.png';
import Path1982Image from 'src/assets/images/VirtusigDashboard_Path_198_1.png';
import Path1992Image from 'src/assets/images/VirtusigDashboard_Path_199_1.png';
import Path2002Image from 'src/assets/images/VirtusigDashboard_Path_200_1.png';
import Path2012Image from 'src/assets/images/VirtusigDashboard_Path_201_1.png';
import Path2022Image from 'src/assets/images/VirtusigDashboard_Path_202_1.png';
import Path2032Image from 'src/assets/images/VirtusigDashboard_Path_203_1.png';
import Path2042Image from 'src/assets/images/VirtusigDashboard_Path_204_1.png';
import Path2052Image from 'src/assets/images/VirtusigDashboard_Path_205_1.png';
import Path2062Image from 'src/assets/images/VirtusigDashboard_Path_206_1.png';
import Path3083Image from 'src/assets/images/VirtusigDashboard_Path_308.png';
import Path1943Image from 'src/assets/images/VirtusigDashboard_Path_194.png';
import Path1953Image from 'src/assets/images/VirtusigDashboard_Path_195.png';
import Path1963Image from 'src/assets/images/VirtusigDashboard_Path_196.png';
import Path1973Image from 'src/assets/images/VirtusigDashboard_Path_197.png';
import Path1983Image from 'src/assets/images/VirtusigDashboard_Path_198.png';
import Path1993Image from 'src/assets/images/VirtusigDashboard_Path_199.png';
import Path2003Image from 'src/assets/images/VirtusigDashboard_Path_200.png';
import Path2013Image from 'src/assets/images/VirtusigDashboard_Path_201.png';
import Path2023Image from 'src/assets/images/VirtusigDashboard_Path_202.png';
import Path2033Image from 'src/assets/images/VirtusigDashboard_Path_203.png';
import Path2043Image from 'src/assets/images/VirtusigDashboard_Path_204.png';
import Path2053Image from 'src/assets/images/VirtusigDashboard_Path_205.png';
import Path2063Image from 'src/assets/images/VirtusigDashboard_Path_206.png';
import GraphImage from 'src/assets/images/VirtusigDashboard_graph.png';
import SettingsFill0Wght400Image from 'src/assets/images/VirtusigDashboard_settings_FILL0_wght400_GRAD0_opsz48.png';
import Path561Image from 'src/assets/images/VirtusigDashboard_Path_561.png';
import Path562Image from 'src/assets/images/VirtusigDashboard_Path_562.png';
import Path563Image from 'src/assets/images/VirtusigDashboard_Path_563.png';
import Path564Image from 'src/assets/images/VirtusigDashboard_Path_564.png';
import Path565Image from 'src/assets/images/VirtusigDashboard_Path_565.png';
import Path566Image from 'src/assets/images/VirtusigDashboard_Path_566.png';
import Path567Image from 'src/assets/images/VirtusigDashboard_Path_567.png';
import Path568Image from 'src/assets/images/VirtusigDashboard_Path_568.png';
import Path569Image from 'src/assets/images/VirtusigDashboard_Path_569.png';
import Path570Image from 'src/assets/images/VirtusigDashboard_Path_570.png';
import Path571Image from 'src/assets/images/VirtusigDashboard_Path_571.png';
import Path572Image from 'src/assets/images/VirtusigDashboard_Path_572.png';
import Path573Image from 'src/assets/images/VirtusigDashboard_Path_573.png';
import Path574Image from 'src/assets/images/VirtusigDashboard_Path_574.png';
import Path575Image from 'src/assets/images/VirtusigDashboard_Path_575.png';
import Path576Image from 'src/assets/images/VirtusigDashboard_Path_576.png';
import Path577Image from 'src/assets/images/VirtusigDashboard_Path_577.png';
import Path578Image from 'src/assets/images/VirtusigDashboard_Path_578.png';
import Path579Image from 'src/assets/images/VirtusigDashboard_Path_579.png';
import Path580Image from 'src/assets/images/VirtusigDashboard_Path_580.png';
import Path581Image from 'src/assets/images/VirtusigDashboard_Path_581.png';
import Path582Image from 'src/assets/images/VirtusigDashboard_Path_582.png';
import Path583Image from 'src/assets/images/VirtusigDashboard_Path_583.png';
import Path584Image from 'src/assets/images/VirtusigDashboard_Path_584.png';
import Path585Image from 'src/assets/images/VirtusigDashboard_Path_585.png';
import Path586Image from 'src/assets/images/VirtusigDashboard_Path_586.png';
import Path587Image from 'src/assets/images/VirtusigDashboard_Path_587.png';
import Path588Image from 'src/assets/images/VirtusigDashboard_Path_588.png';
import Path589Image from 'src/assets/images/VirtusigDashboard_Path_589.png';
import Path590Image from 'src/assets/images/VirtusigDashboard_Path_590.png';
import Path591Image from 'src/assets/images/VirtusigDashboard_Path_591.png';
import Path633Image from 'src/assets/images/VirtusigDashboard_Path_633.png';
import Path634Image from 'src/assets/images/VirtusigDashboard_Path_634.png';
import Path635Image from 'src/assets/images/VirtusigDashboard_Path_635.png';
import Path636Image from 'src/assets/images/VirtusigDashboard_Path_636.png';
import Path637Image from 'src/assets/images/VirtusigDashboard_Path_637.png';
import Path638Image from 'src/assets/images/VirtusigDashboard_Path_638.png';
import Ellipse40Image from 'src/assets/images/VirtusigDashboard_Ellipse_40.png';
import Path639Image from 'src/assets/images/VirtusigDashboard_Path_639.png';
import Path640Image from 'src/assets/images/VirtusigDashboard_Path_640.png';
import Path641Image from 'src/assets/images/VirtusigDashboard_Path_641.png';
import Path642Image from 'src/assets/images/VirtusigDashboard_Path_642.png';
import Path643Image from 'src/assets/images/VirtusigDashboard_Path_643.png';
import Path644Image from 'src/assets/images/VirtusigDashboard_Path_644.png';
import Path645Image from 'src/assets/images/VirtusigDashboard_Path_645.png';
import Path646Image from 'src/assets/images/VirtusigDashboard_Path_646.png';
import Path647Image from 'src/assets/images/VirtusigDashboard_Path_647.png';
import Path648Image from 'src/assets/images/VirtusigDashboard_Path_648.png';
import Path649Image from 'src/assets/images/VirtusigDashboard_Path_649.png';
import OnedriveSvgrepoComImage from 'src/assets/images/VirtusigDashboard_onedrive_svgrepo_com.png';
import ThreeDotsSvgrepoComImage from 'src/assets/images/VirtusigDashboard_three_dots_svgrepo_com.png';
import Ellipse41Image from 'src/assets/images/VirtusigDashboard_Ellipse_41.png';
import Path655Image from 'src/assets/images/VirtusigDashboard_Path_655.png';
import { styled } from '@mui/material/styles';
import { VirtusigDashboardProps } from 'src/types';
import { animated, useSpring, easings } from 'react-spring';
import useVirtusigDashboard from 'src/components/VirtusigDashboard/useVirtusigDashboard';

const VirtusigDashboard1: any = styled('div')({
  backgroundColor: `rgba(241, 241, 241, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: `1920px`,
  height: `1627px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Rectangle387: any = styled('div')({
  backgroundColor: `rgba(56, 33, 87, 1)`,
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `1920px`,
  height: `442px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const VirtusigLogo2: any = styled('img')({
  height: `103px`,
  width: `82px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `19px`,
  top: `3px`,
});

const Line58: any = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  width: `1832px`,
  height: `0px`,
  position: `absolute`,
  left: `34px`,
  top: `110px`,
});

const Rectangle388: any = styled('div')({
  opacity: `0.8199999928474426`,
  backgroundColor: `rgba(107, 75, 148, 1)`,
  boxShadow: `0px 3px 3px rgba(255, 255, 255, 0.89)`,
  borderRadius: `14px`,
  width: `1806px`,
  height: `163px`,
  position: `absolute`,
  left: `57px`,
  top: `221px`,
});

const Line59: any = styled('div')({
  border: `1px solid rgba(255, 255, 255, 1)`,
  width: `113px`,
  height: `0px`,
  position: `absolute`,
  left: `555px`,
  top: `307px`,
});

const Line60: any = styled('div')({
  border: `1px solid rgba(255, 255, 255, 1)`,
  width: `113px`,
  height: `0px`,
  position: `absolute`,
  left: `1009px`,
  top: `307px`,
});

const Line61: any = styled('div')({
  border: `1px solid rgba(255, 255, 255, 1)`,
  width: `113px`,
  height: `0px`,
  position: `absolute`,
  left: `1451px`,
  top: `307px`,
});

const Dashboard: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `61px`,
  textTransform: `none`,
  position: `absolute`,
  left: `246px`,
  top: `32px`,
});

const Manage: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(155, 155, 155, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `61px`,
  textTransform: `none`,
  position: `absolute`,
  left: `499px`,
  top: `32px`,
});

const Template: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(155, 155, 155, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `61px`,
  textTransform: `none`,
  position: `absolute`,
  left: `750px`,
  top: `32px`,
});

const Settings: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(155, 155, 155, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `61px`,
  textTransform: `none`,
  position: `absolute`,
  left: `994px`,
  top: `32px`,
});

const Frame4: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `92px`,
  top: `234px`,
});

const Frame3: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `74px`,
  width: `249px`,
  margin: `0px`,
});

const ActionRequired: any = styled('content')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(219, 213, 246, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `34px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `74px`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame2: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `74px`,
  width: `48px`,
  margin: `0px`,
});

const Q01: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `700`,
  fontSize: `40px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `74px`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Q04: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `700`,
  fontSize: `40px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `74px`,
  textTransform: `none`,
  position: `absolute`,
  left: `532px`,
  top: `301px`,
});

const Q03: any = styled('div', {
  shouldForwardProp: (prop: any) => !['fns'].includes(prop.toString()),
})(({ fns }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: fns.getCompletedColor(),
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `700`,
  fontSize: `40px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `74px`,
  textTransform: `none`,
  position: `absolute`,
  left: `986px`,
  top: `298px`,
}));

const Q011: any = styled('div', {
  shouldForwardProp: (prop: any) => !['fns'].includes(prop.toString()),
})(({ fns }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: fns.getExpiredColor(),
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `700`,
  fontSize: `40px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `74px`,
  textTransform: `none`,
  position: `absolute`,
  left: `1440px`,
  top: `303px`,
}));

const WaitingForOthers: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(219, 213, 246, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `34px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `74px`,
  textTransform: `none`,
  position: `absolute`,
  left: `532px`,
  top: `234px`,
});

const Completed: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(219, 213, 246, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `34px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `74px`,
  textTransform: `none`,
  position: `absolute`,
  left: `986px`,
  top: `234px`,
});

const Expired: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(219, 213, 246, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `34px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `74px`,
  textTransform: `none`,
  position: `absolute`,
  left: `1440px`,
  top: `234px`,
});

const Rectangle389: any = styled('div', {
  shouldForwardProp: (prop: any) => !['fns'].includes(prop.toString()),
})(({ fns }: any) => ({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `0px 3px 3px rgba(0, 0, 0, 0.16)`,
  borderRadius: `8px`,
  width: `612px`,
  height: `510px`,
  position: `absolute`,
  left: `43px`,
  top: `482px`,
  backgroundClip: fns.getBackgroundClip(),
}));

const Rectangle396: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `0px 3px 3px rgba(0, 0, 0, 0.16)`,
  borderRadius: `8px`,
  width: `610px`,
  height: `565px`,
  position: `absolute`,
  left: `43px`,
  top: `1012px`,
});

const Rectangle397: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `0px 3px 3px rgba(0, 0, 0, 0.16)`,
  borderRadius: `8px`,
  width: `1176px`,
  height: `565px`,
  position: `absolute`,
  left: `705px`,
  top: `1012px`,
});

const FileUpload: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(6, 5, 6, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `34px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `74px`,
  textTransform: `none`,
  position: `absolute`,
  left: `92px`,
  top: `481px`,
});

const QuickStats: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(56, 33, 87, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `34px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `74px`,
  textTransform: `none`,
  position: `absolute`,
  left: `92px`,
  top: `1025px`,
});

const AverageEnvelopsSent: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(56, 33, 87, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `34px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `57px`,
  textTransform: `none`,
  position: `absolute`,
  left: `748px`,
  top: `1031px`,
});

const RecentActivities: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(6, 5, 6, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `34px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `74px`,
  textTransform: `none`,
  position: `absolute`,
  left: `725px`,
  top: `478px`,
});

const FolderSvgrepoCom: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `140.12px`,
  height: `126.98px`,
  left: `265px`,
  top: `635px`,
});

const Path556: any = styled('img')({
  height: `48.24px`,
  width: `113.85px`,
  position: `absolute`,
  left: `13px`,
  top: `0px`,
});

const Path557: any = styled('img')({
  height: `35.03px`,
  width: `113.85px`,
  position: `absolute`,
  left: `13px`,
  top: `26px`,
});

const Path558: any = styled('img')({
  height: `52.55px`,
  width: `52.55px`,
  position: `absolute`,
  left: `88px`,
  top: `74px`,
});

const Path559: any = styled('img')({
  height: `26.27px`,
  width: `26.27px`,
  position: `absolute`,
  left: `101px`,
  top: `88px`,
});

const Path560: any = styled('img')({
  height: `91.95px`,
  width: `140.12px`,
  position: `absolute`,
  left: `0px`,
  top: `35px`,
});

const Rectangle390: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(97, 67, 137, 1)`,
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  borderRadius: `9px`,
  width: `208px`,
  height: `67px`,
  position: `absolute`,
  left: `235px`,
  top: `860px`,
}));

const Upload: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(250, 250, 250, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `74px`,
  textTransform: `none`,
  position: `absolute`,
  left: `291px`,
  top: `858px`,
});

const Upload1: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(203, 49, 49, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `74px`,
  textTransform: `none`,
  position: `absolute`,
  left: `268px`,
  top: `914px`,
});

const Rectangle392: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `0px 3px 3px rgba(0, 0, 0, 0.16)`,
  borderRadius: `12px`,
  width: `485px`,
  height: `177px`,
  position: `absolute`,
  left: `730px`,
  top: `553px`,
});

const Rectangle394: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `0px 3px 3px rgba(0, 0, 0, 0.16)`,
  borderRadius: `12px`,
  width: `485px`,
  height: `177px`,
  position: `absolute`,
  left: `1356px`,
  top: `553px`,
});

const Rectangle395: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `0px 3px 3px rgba(0, 0, 0, 0.16)`,
  borderRadius: `12px`,
  width: `485px`,
  height: `177px`,
  position: `absolute`,
  left: `1356px`,
  top: `772px`,
});

const Rectangle393: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `0px 3px 3px rgba(0, 0, 0, 0.16)`,
  borderRadius: `12px`,
  width: `485px`,
  height: `177px`,
  position: `absolute`,
  left: `730px`,
  top: `772px`,
});

const Aug23: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(119, 120, 121, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `35px`,
  textTransform: `none`,
  position: `absolute`,
  left: `804px`,
  top: `1516px`,
});

const Aug28: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(119, 120, 121, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `35px`,
  textTransform: `none`,
  position: `absolute`,
  left: `911px`,
  top: `1516px`,
});

const Sept2: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(119, 120, 121, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `35px`,
  textTransform: `none`,
  position: `absolute`,
  left: `1016px`,
  top: `1516px`,
});

const Sept7: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(119, 120, 121, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `35px`,
  textTransform: `none`,
  position: `absolute`,
  left: `1109px`,
  top: `1516px`,
});

const Sept12: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(119, 120, 121, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `35px`,
  textTransform: `none`,
  position: `absolute`,
  left: `1206px`,
  top: `1516px`,
});

const Sept17: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(119, 120, 121, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `35px`,
  textTransform: `none`,
  position: `absolute`,
  left: `1309px`,
  top: `1516px`,
});

const Sept22: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(119, 120, 121, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `35px`,
  textTransform: `none`,
  position: `absolute`,
  left: `1412px`,
  top: `1516px`,
});

const Sept27: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(119, 120, 121, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `35px`,
  textTransform: `none`,
  position: `absolute`,
  left: `1530px`,
  top: `1515px`,
});

const Line31: any = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  width: `889.5px`,
  height: `0px`,
  position: `absolute`,
  left: `790px`,
  top: `1510px`,
});

const Line32: any = styled('div')({
  border: `0.25px solid rgba(112, 112, 112, 1)`,
  width: `390px`,
  height: `0px`,
  position: `absolute`,
  left: `984px`,
  top: `1314px`,
});

const Q1: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(119, 120, 121, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `35px`,
  textTransform: `none`,
  position: `absolute`,
  left: `768px`,
  top: `1442px`,
});

const Q2: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(119, 120, 121, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `35px`,
  textTransform: `none`,
  position: `absolute`,
  left: `768px`,
  top: `1388px`,
});

const Q3: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(119, 120, 121, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `35px`,
  textTransform: `none`,
  position: `absolute`,
  left: `768px`,
  top: `1332px`,
});

const Q4: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(119, 120, 121, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `35px`,
  textTransform: `none`,
  position: `absolute`,
  left: `768px`,
  top: `1281px`,
});

const Q5: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(119, 120, 121, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `35px`,
  textTransform: `none`,
  position: `absolute`,
  left: `768px`,
  top: `1231px`,
});

const Q6: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(119, 120, 121, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `35px`,
  textTransform: `none`,
  position: `absolute`,
  left: `768px`,
  top: `1175px`,
});

const Q7: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(119, 120, 121, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `35px`,
  textTransform: `none`,
  position: `absolute`,
  left: `768px`,
  top: `1121px`,
});

const Rectangle398: any = styled('div')({
  backgroundColor: `rgba(129, 113, 234, 1)`,
  borderRadius: `5px 5px 0px 0px`,
  width: `25px`,
  height: `345px`,
  position: `absolute`,
  left: `811px`,
  top: `1164px`,
});

const Rectangle399: any = styled('div')({
  backgroundColor: `rgba(129, 113, 234, 1)`,
  borderRadius: `5px 5px 0px 0px`,
  width: `25px`,
  height: `253px`,
  position: `absolute`,
  left: `839px`,
  top: `1257px`,
});

const Rectangle400: any = styled('div')({
  backgroundColor: `rgba(129, 113, 234, 1)`,
  borderRadius: `5px 5px 0px 0px`,
  width: `25px`,
  height: `212px`,
  position: `absolute`,
  left: `867px`,
  top: `1298px`,
});

const Rectangle401: any = styled('div')({
  backgroundColor: `rgba(129, 113, 234, 1)`,
  borderRadius: `5px 5px 0px 0px`,
  width: `25px`,
  height: `127px`,
  position: `absolute`,
  left: `926px`,
  top: `1383px`,
});

const Rectangle402: any = styled('div')({
  backgroundColor: `rgba(129, 113, 234, 1)`,
  borderRadius: `5px 5px 0px 0px`,
  width: `25px`,
  height: `261px`,
  position: `absolute`,
  left: `955px`,
  top: `1248px`,
});

const Rectangle403: any = styled('div')({
  backgroundColor: `rgba(129, 113, 234, 1)`,
  borderRadius: `5px 5px 0px 0px`,
  width: `25px`,
  height: `326px`,
  position: `absolute`,
  left: `984px`,
  top: `1183px`,
});

const Rectangle404: any = styled('div')({
  backgroundColor: `rgba(129, 113, 234, 1)`,
  borderRadius: `5px 5px 0px 0px`,
  width: `25px`,
  height: `326px`,
  position: `absolute`,
  left: `1043px`,
  top: `1184px`,
});

const Rectangle405: any = styled('div')({
  backgroundColor: `rgba(129, 113, 234, 1)`,
  borderRadius: `5px 5px 0px 0px`,
  width: `25px`,
  height: `221px`,
  position: `absolute`,
  left: `1074px`,
  top: `1289px`,
});

const Rectangle406: any = styled('div')({
  backgroundColor: `rgba(129, 113, 234, 1)`,
  borderRadius: `5px 5px 0px 0px`,
  width: `25px`,
  height: `263px`,
  position: `absolute`,
  left: `1105px`,
  top: `1248px`,
});

const Rectangle407: any = styled('div')({
  backgroundColor: `rgba(129, 113, 234, 1)`,
  borderRadius: `5px 5px 0px 0px`,
  width: `25px`,
  height: `263px`,
  position: `absolute`,
  left: `1166px`,
  top: `1248px`,
});

const Rectangle410: any = styled('div')({
  backgroundColor: `rgba(129, 113, 234, 1)`,
  borderRadius: `5px 5px 0px 0px`,
  width: `25px`,
  height: `263px`,
  position: `absolute`,
  left: `1293px`,
  top: `1248px`,
});

const Rectangle411: any = styled('div')({
  backgroundColor: `rgba(129, 113, 234, 1)`,
  borderRadius: `5px 5px 0px 0px`,
  width: `25px`,
  height: `158px`,
  position: `absolute`,
  left: `1354px`,
  top: `1353px`,
});

const Rectangle413: any = styled('div')({
  backgroundColor: `rgba(129, 113, 234, 1)`,
  borderRadius: `5px 5px 0px 0px`,
  width: `25px`,
  height: `79px`,
  position: `absolute`,
  left: `1395px`,
  top: `1432px`,
});

const Rectangle414: any = styled('div')({
  backgroundColor: `rgba(129, 113, 234, 1)`,
  borderRadius: `5px 5px 0px 0px`,
  width: `25px`,
  height: `58px`,
  position: `absolute`,
  left: `1424px`,
  top: `1453px`,
});

const Rectangle415: any = styled('div')({
  backgroundColor: `rgba(129, 113, 234, 1)`,
  borderRadius: `5px 5px 0px 0px`,
  width: `25px`,
  height: `114px`,
  position: `absolute`,
  left: `1453px`,
  top: `1396px`,
});

const Rectangle416: any = styled('div')({
  backgroundColor: `rgba(129, 113, 234, 1)`,
  borderRadius: `5px 5px 0px 0px`,
  width: `25px`,
  height: `172px`,
  position: `absolute`,
  left: `1522px`,
  top: `1337px`,
});

const Rectangle417: any = styled('div')({
  backgroundColor: `rgba(129, 113, 234, 1)`,
  borderRadius: `5px 5px 0px 0px`,
  width: `25px`,
  height: `96px`,
  position: `absolute`,
  left: `1584px`,
  top: `1415px`,
});

const Rectangle418: any = styled('div')({
  backgroundColor: `rgba(129, 113, 234, 1)`,
  borderRadius: `5px 5px 0px 0px`,
  width: `25px`,
  height: `212px`,
  position: `absolute`,
  left: `1553px`,
  top: `1299px`,
});

const Rectangle412: any = styled('div')({
  backgroundColor: `rgba(129, 113, 234, 1)`,
  borderRadius: `5px 5px 0px 0px`,
  width: `25px`,
  height: `132px`,
  position: `absolute`,
  left: `1323px`,
  top: `1379px`,
});

const Rectangle408: any = styled('div')({
  backgroundColor: `rgba(129, 113, 234, 1)`,
  borderRadius: `5px 5px 0px 0px`,
  width: `25px`,
  height: `115px`,
  position: `absolute`,
  left: `1195px`,
  top: `1396px`,
});

const Rectangle409: any = styled('div')({
  backgroundColor: `rgba(129, 113, 234, 1)`,
  borderRadius: `5px 5px 0px 0px`,
  width: `25px`,
  height: `82px`,
  position: `absolute`,
  left: `1224px`,
  top: `1429px`,
});

const ManikandaRaman: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(6, 5, 6, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `27px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `59px`,
  textTransform: `none`,
  position: `absolute`,
  left: `757px`,
  top: `551px`,
});

const SentOnDdMmYyyy: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(126, 126, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `39px`,
  textTransform: `none`,
  position: `absolute`,
  left: `757px`,
  top: `602px`,
});

const SentOnDdMmYyyy1: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(126, 126, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `39px`,
  textTransform: `none`,
  position: `absolute`,
  left: `1381px`,
  top: `601px`,
});

const SentOnDdMmYyyy2: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(126, 126, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `39px`,
  textTransform: `none`,
  position: `absolute`,
  left: `1381px`,
  top: `819px`,
});

const SentOnDdMmYyyy3: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(126, 126, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `39px`,
  textTransform: `none`,
  position: `absolute`,
  left: `757px`,
  top: `830px`,
});

const RajeshManoharan: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(6, 5, 6, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `27px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `59px`,
  textTransform: `none`,
  position: `absolute`,
  left: `1381px`,
  top: `558px`,
});

const VigneshVicky: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(6, 5, 6, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `27px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `59px`,
  textTransform: `none`,
  position: `absolute`,
  left: `755px`,
  top: `784px`,
});

const AzifAli: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(6, 5, 6, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `27px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `59px`,
  textTransform: `none`,
  position: `absolute`,
  left: `1381px`,
  top: `776px`,
});

const AvatarSvgrepoCom5: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `73.22px`,
  height: `70.94px`,
  left: `739px`,
  top: `649px`,
});

const Path308: any = styled('img')({
  height: `70.94px`,
  width: `73.22px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group12: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `41.47px`,
  height: `51.34px`,
  left: `16px`,
  top: `8px`,
});

const Group11: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `41.47px`,
  height: `51.34px`,
  left: `0px`,
  top: `0px`,
});

const Group10: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `41.47px`,
  height: `51.06px`,
  left: `0px`,
  top: `0px`,
});

const Path194: any = styled('img')({
  height: `20.68px`,
  width: `41.47px`,
  position: `absolute`,
  left: `0px`,
  top: `30px`,
});

const Path195: any = styled('img')({
  height: `20.68px`,
  width: `20.74px`,
  position: `absolute`,
  left: `21px`,
  top: `30px`,
});

const Rectangle31: any = styled('div')({
  backgroundColor: `rgba(241, 201, 165, 1)`,
  width: `8.26px`,
  height: `13.39px`,
  position: `absolute`,
  left: `17px`,
  top: `22px`,
});

const Rectangle32: any = styled('div')({
  backgroundColor: `rgba(228, 182, 146, 1)`,
  width: `4.13px`,
  height: `13.39px`,
  position: `absolute`,
  left: `21px`,
  top: `22px`,
});

const Path196: any = styled('img')({
  height: `9.46px`,
  width: `8.26px`,
  position: `absolute`,
  left: `17px`,
  top: `22px`,
});

const Path197: any = styled('img')({
  height: `28.27px`,
  width: `21.24px`,
  position: `absolute`,
  left: `10px`,
  top: `0px`,
});

const Path198: any = styled('img')({
  height: `8.3px`,
  width: `7.07px`,
  position: `absolute`,
  left: `27px`,
  top: `11px`,
});

const Path199: any = styled('img')({
  height: `8.3px`,
  width: `7.07px`,
  position: `absolute`,
  left: `8px`,
  top: `11px`,
});

const Path200: any = styled('img')({
  height: `28.27px`,
  width: `10.62px`,
  position: `absolute`,
  left: `21px`,
  top: `0px`,
});

const Path201: any = styled('img')({
  height: `19.35px`,
  width: `41.47px`,
  position: `absolute`,
  left: `0px`,
  top: `32px`,
});

const Path202: any = styled('img')({
  height: `17.42px`,
  width: `17.41px`,
  position: `absolute`,
  left: `9px`,
  top: `0px`,
});

const Path203: any = styled('img')({
  height: `14.37px`,
  width: `6.61px`,
  position: `absolute`,
  left: `26px`,
  top: `2px`,
});

const Path204: any = styled('img')({
  height: `8.27px`,
  width: `7.59px`,
  position: `absolute`,
  left: `21px`,
  top: `32px`,
});

const Path205: any = styled('img')({
  height: `14.34px`,
  width: `1.62px`,
  position: `absolute`,
  left: `19px`,
  top: `37px`,
});

const Path206: any = styled('img')({
  height: `8.27px`,
  width: `7.59px`,
  position: `absolute`,
  left: `13px`,
  top: `32px`,
});

const AvatarSvgrepoCom51: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `73.22px`,
  height: `70.94px`,
  left: `1365px`,
  top: `649px`,
});

const Path3081: any = styled('img')({
  height: `70.94px`,
  width: `73.22px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group121: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `41.47px`,
  height: `51.34px`,
  left: `16px`,
  top: `8px`,
});

const Group111: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `41.47px`,
  height: `51.34px`,
  left: `0px`,
  top: `0px`,
});

const Group101: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `41.47px`,
  height: `51.06px`,
  left: `0px`,
  top: `0px`,
});

const Path1941: any = styled('img')({
  height: `20.68px`,
  width: `41.47px`,
  position: `absolute`,
  left: `0px`,
  top: `30px`,
});

const Path1951: any = styled('img')({
  height: `20.68px`,
  width: `20.74px`,
  position: `absolute`,
  left: `21px`,
  top: `30px`,
});

const Rectangle311: any = styled('div')({
  backgroundColor: `rgba(241, 201, 165, 1)`,
  width: `8.26px`,
  height: `13.39px`,
  position: `absolute`,
  left: `17px`,
  top: `22px`,
});

const Rectangle321: any = styled('div')({
  backgroundColor: `rgba(228, 182, 146, 1)`,
  width: `4.13px`,
  height: `13.39px`,
  position: `absolute`,
  left: `21px`,
  top: `22px`,
});

const Path1961: any = styled('img')({
  height: `9.46px`,
  width: `8.26px`,
  position: `absolute`,
  left: `17px`,
  top: `22px`,
});

const Path1971: any = styled('img')({
  height: `28.27px`,
  width: `21.24px`,
  position: `absolute`,
  left: `10px`,
  top: `0px`,
});

const Path1981: any = styled('img')({
  height: `8.3px`,
  width: `7.07px`,
  position: `absolute`,
  left: `27px`,
  top: `11px`,
});

const Path1991: any = styled('img')({
  height: `8.3px`,
  width: `7.07px`,
  position: `absolute`,
  left: `8px`,
  top: `11px`,
});

const Path2001: any = styled('img')({
  height: `28.27px`,
  width: `10.62px`,
  position: `absolute`,
  left: `21px`,
  top: `0px`,
});

const Path2011: any = styled('img')({
  height: `19.35px`,
  width: `41.47px`,
  position: `absolute`,
  left: `0px`,
  top: `32px`,
});

const Path2021: any = styled('img')({
  height: `17.42px`,
  width: `17.41px`,
  position: `absolute`,
  left: `9px`,
  top: `0px`,
});

const Path2031: any = styled('img')({
  height: `14.37px`,
  width: `6.61px`,
  position: `absolute`,
  left: `26px`,
  top: `2px`,
});

const Path2041: any = styled('img')({
  height: `8.27px`,
  width: `7.59px`,
  position: `absolute`,
  left: `21px`,
  top: `32px`,
});

const Path2051: any = styled('img')({
  height: `14.34px`,
  width: `1.62px`,
  position: `absolute`,
  left: `19px`,
  top: `37px`,
});

const Path2061: any = styled('img')({
  height: `8.27px`,
  width: `7.59px`,
  position: `absolute`,
  left: `13px`,
  top: `32px`,
});

const AvatarSvgrepoCom52: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `73.22px`,
  height: `70.94px`,
  left: `1365px`,
  top: `867px`,
});

const Path3082: any = styled('img')({
  height: `70.94px`,
  width: `73.22px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group122: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `41.47px`,
  height: `51.34px`,
  left: `16px`,
  top: `7px`,
});

const Group112: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `41.47px`,
  height: `51.34px`,
  left: `0px`,
  top: `0px`,
});

const Group102: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `41.47px`,
  height: `51.06px`,
  left: `0px`,
  top: `0px`,
});

const Path1942: any = styled('img')({
  height: `20.68px`,
  width: `41.47px`,
  position: `absolute`,
  left: `0px`,
  top: `30px`,
});

const Path1952: any = styled('img')({
  height: `20.68px`,
  width: `20.74px`,
  position: `absolute`,
  left: `21px`,
  top: `30px`,
});

const Rectangle312: any = styled('div')({
  backgroundColor: `rgba(241, 201, 165, 1)`,
  width: `8.26px`,
  height: `13.39px`,
  position: `absolute`,
  left: `17px`,
  top: `22px`,
});

const Rectangle322: any = styled('div')({
  backgroundColor: `rgba(228, 182, 146, 1)`,
  width: `4.13px`,
  height: `13.39px`,
  position: `absolute`,
  left: `21px`,
  top: `22px`,
});

const Path1962: any = styled('img')({
  height: `9.46px`,
  width: `8.26px`,
  position: `absolute`,
  left: `17px`,
  top: `22px`,
});

const Path1972: any = styled('img')({
  height: `28.27px`,
  width: `21.24px`,
  position: `absolute`,
  left: `10px`,
  top: `0px`,
});

const Path1982: any = styled('img')({
  height: `8.3px`,
  width: `7.07px`,
  position: `absolute`,
  left: `27px`,
  top: `11px`,
});

const Path1992: any = styled('img')({
  height: `8.3px`,
  width: `7.07px`,
  position: `absolute`,
  left: `8px`,
  top: `11px`,
});

const Path2002: any = styled('img')({
  height: `28.27px`,
  width: `10.62px`,
  position: `absolute`,
  left: `21px`,
  top: `0px`,
});

const Path2012: any = styled('img')({
  height: `19.35px`,
  width: `41.47px`,
  position: `absolute`,
  left: `0px`,
  top: `32px`,
});

const Path2022: any = styled('img')({
  height: `17.42px`,
  width: `17.41px`,
  position: `absolute`,
  left: `9px`,
  top: `0px`,
});

const Path2032: any = styled('img')({
  height: `14.37px`,
  width: `6.61px`,
  position: `absolute`,
  left: `26px`,
  top: `2px`,
});

const Path2042: any = styled('img')({
  height: `8.27px`,
  width: `7.59px`,
  position: `absolute`,
  left: `21px`,
  top: `32px`,
});

const Path2052: any = styled('img')({
  height: `14.34px`,
  width: `1.62px`,
  position: `absolute`,
  left: `19px`,
  top: `37px`,
});

const Path2062: any = styled('img')({
  height: `8.27px`,
  width: `7.59px`,
  position: `absolute`,
  left: `13px`,
  top: `32px`,
});

const AvatarSvgrepoCom53: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `73.22px`,
  height: `70.94px`,
  left: `739px`,
  top: `871px`,
});

const Path3083: any = styled('img')({
  height: `70.94px`,
  width: `73.22px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group123: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `41.47px`,
  height: `51.34px`,
  left: `16px`,
  top: `8px`,
});

const Group113: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `41.47px`,
  height: `51.34px`,
  left: `0px`,
  top: `0px`,
});

const Group103: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `41.47px`,
  height: `51.06px`,
  left: `0px`,
  top: `0px`,
});

const Path1943: any = styled('img')({
  height: `20.68px`,
  width: `41.47px`,
  position: `absolute`,
  left: `0px`,
  top: `30px`,
});

const Path1953: any = styled('img')({
  height: `20.68px`,
  width: `20.74px`,
  position: `absolute`,
  left: `21px`,
  top: `30px`,
});

const Rectangle313: any = styled('div')({
  backgroundColor: `rgba(241, 201, 165, 1)`,
  width: `8.26px`,
  height: `13.39px`,
  position: `absolute`,
  left: `17px`,
  top: `22px`,
});

const Rectangle323: any = styled('div')({
  backgroundColor: `rgba(228, 182, 146, 1)`,
  width: `4.13px`,
  height: `13.39px`,
  position: `absolute`,
  left: `21px`,
  top: `22px`,
});

const Path1963: any = styled('img')({
  height: `9.46px`,
  width: `8.26px`,
  position: `absolute`,
  left: `17px`,
  top: `22px`,
});

const Path1973: any = styled('img')({
  height: `28.27px`,
  width: `21.24px`,
  position: `absolute`,
  left: `10px`,
  top: `0px`,
});

const Path1983: any = styled('img')({
  height: `8.3px`,
  width: `7.07px`,
  position: `absolute`,
  left: `27px`,
  top: `11px`,
});

const Path1993: any = styled('img')({
  height: `8.3px`,
  width: `7.07px`,
  position: `absolute`,
  left: `8px`,
  top: `11px`,
});

const Path2003: any = styled('img')({
  height: `28.27px`,
  width: `10.62px`,
  position: `absolute`,
  left: `21px`,
  top: `0px`,
});

const Path2013: any = styled('img')({
  height: `19.35px`,
  width: `41.47px`,
  position: `absolute`,
  left: `0px`,
  top: `32px`,
});

const Path2023: any = styled('img')({
  height: `17.42px`,
  width: `17.41px`,
  position: `absolute`,
  left: `9px`,
  top: `0px`,
});

const Path2033: any = styled('img')({
  height: `14.37px`,
  width: `6.61px`,
  position: `absolute`,
  left: `26px`,
  top: `2px`,
});

const Path2043: any = styled('img')({
  height: `8.27px`,
  width: `7.59px`,
  position: `absolute`,
  left: `21px`,
  top: `32px`,
});

const Path2053: any = styled('img')({
  height: `14.34px`,
  width: `1.62px`,
  position: `absolute`,
  left: `19px`,
  top: `37px`,
});

const Path2063: any = styled('img')({
  height: `8.27px`,
  width: `7.59px`,
  position: `absolute`,
  left: `13px`,
  top: `32px`,
});

const Rectangle419: any = styled('div')({
  backgroundColor: `rgba(67, 137, 100, 1)`,
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  borderRadius: `9px`,
  width: `116px`,
  height: `37px`,
  position: `absolute`,
  left: `1068px`,
  top: `672px`,
});

const Rectangle421: any = styled('div')({
  backgroundColor: `rgba(67, 137, 100, 1)`,
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  borderRadius: `9px`,
  width: `116px`,
  height: `37px`,
  position: `absolute`,
  left: `1697px`,
  top: `672px`,
});

const Rectangle422: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(97, 67, 137, 1)`,
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  borderRadius: `9px`,
  width: `116px`,
  height: `37px`,
  position: `absolute`,
  left: `1696px`,
  top: `888px`,
}));

const Rectangle420: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(97, 67, 137, 1)`,
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  borderRadius: `9px`,
  width: `116px`,
  height: `37px`,
  position: `absolute`,
  left: `1068px`,
  top: `888px`,
}));

const Graph: any = animated(
  styled('img')({
    height: `446px`,
    width: `482px`,
    objectFit: `cover`,
    position: `absolute`,
    left: `116px`,
    top: `1105px`,
  })
);

const Line62: any = styled('div')({
  border: `5px solid rgba(178, 136, 235, 1)`,
  width: `165px`,
  height: `0px`,
  position: `absolute`,
  left: `238px`,
  top: `94px`,
});

const SettingsFill0Wght400: any = styled('img')({
  height: `28px`,
  width: `28px`,
  position: `absolute`,
  left: `1699px`,
  top: `49px`,
});

const NotificationAlarmBel: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `24.92px`,
  height: `27px`,
  left: `1765px`,
  top: `50px`,
});

const Path561: any = styled('img')({
  height: `22.85px`,
  width: `24.92px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Path562: any = styled('img')({
  height: `4.15px`,
  width: `8.31px`,
  position: `absolute`,
  left: `8px`,
  top: `23px`,
});

const SearchSvgrepoCom7: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `32.03px`,
  height: `32px`,
  left: `1556px`,
  top: `47px`,
});

const Group127: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `32.03px`,
  height: `32px`,
  left: `0px`,
  top: `0px`,
});

const Path563: any = styled('img')({
  height: `32px`,
  width: `32.03px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const FlagForUnitedStatesS: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `36.7px`,
  height: `36.7px`,
  left: `1627px`,
  top: `44px`,
});

const Path564: any = styled('img')({
  height: `2.81px`,
  width: `9.79px`,
  position: `absolute`,
  left: `18px`,
  top: `0px`,
});

const Path565: any = styled('img')({
  height: `2.81px`,
  width: `13.21px`,
  position: `absolute`,
  left: `18px`,
  top: `3px`,
});

const Path566: any = styled('img')({
  height: `2.81px`,
  width: `15.47px`,
  position: `absolute`,
  left: `18px`,
  top: `6px`,
});

const Path567: any = styled('img')({
  height: `2.81px`,
  width: `16.94px`,
  position: `absolute`,
  left: `18px`,
  top: `8px`,
});

const Path568: any = styled('img')({
  height: `2.81px`,
  width: `17.86px`,
  position: `absolute`,
  left: `18px`,
  top: `11px`,
});

const Path569: any = styled('img')({
  height: `2.81px`,
  width: `18.29px`,
  position: `absolute`,
  left: `18px`,
  top: `14px`,
});

const Path570: any = styled('img')({
  height: `2.81px`,
  width: `36.7px`,
  position: `absolute`,
  left: `0px`,
  top: `17px`,
});

const Path571: any = styled('img')({
  height: `2.81px`,
  width: `36.58px`,
  position: `absolute`,
  left: `0px`,
  top: `20px`,
});

const Path572: any = styled('img')({
  height: `2.81px`,
  width: `35.72px`,
  position: `absolute`,
  left: `0px`,
  top: `23px`,
});

const Path573: any = styled('img')({
  height: `2.81px`,
  width: `33.89px`,
  position: `absolute`,
  left: `1px`,
  top: `25px`,
});

const Path574: any = styled('img')({
  height: `2.81px`,
  width: `30.95px`,
  position: `absolute`,
  left: `3px`,
  top: `28px`,
});

const Path575: any = styled('img')({
  height: `2.81px`,
  width: `26.55px`,
  position: `absolute`,
  left: `5px`,
  top: `31px`,
});

const Path576: any = styled('img')({
  height: `2.87px`,
  width: `19.7px`,
  position: `absolute`,
  left: `9px`,
  top: `34px`,
});

const Path577: any = styled('img')({
  height: `18.35px`,
  width: `18.35px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group128: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `16.88px`,
  height: `17.13px`,
  left: `1px`,
  top: `1px`,
});

const Path578: any = styled('img')({
  height: `2.45px`,
  width: `2.45px`,
  position: `absolute`,
  left: `12px`,
  top: `0px`,
});

const Path579: any = styled('img')({
  height: `2.45px`,
  width: `2.45px`,
  position: `absolute`,
  left: `14px`,
  top: `4px`,
});

const Path580: any = styled('img')({
  height: `2.45px`,
  width: `2.45px`,
  position: `absolute`,
  left: `10px`,
  top: `4px`,
});

const Path581: any = styled('img')({
  height: `2.45px`,
  width: `2.45px`,
  position: `absolute`,
  left: `12px`,
  top: `7px`,
});

const Path582: any = styled('img')({
  height: `2.45px`,
  width: `2.45px`,
  position: `absolute`,
  left: `7px`,
  top: `7px`,
});

const Path583: any = styled('img')({
  height: `2.45px`,
  width: `2.45px`,
  position: `absolute`,
  left: `2px`,
  top: `7px`,
});

const Path584: any = styled('img')({
  height: `2.45px`,
  width: `2.45px`,
  position: `absolute`,
  left: `14px`,
  top: `11px`,
});

const Path585: any = styled('img')({
  height: `2.45px`,
  width: `2.45px`,
  position: `absolute`,
  left: `10px`,
  top: `11px`,
});

const Path586: any = styled('img')({
  height: `2.45px`,
  width: `2.45px`,
  position: `absolute`,
  left: `5px`,
  top: `11px`,
});

const Path587: any = styled('img')({
  height: `2.45px`,
  width: `2.45px`,
  position: `absolute`,
  left: `12px`,
  top: `15px`,
});

const Path588: any = styled('img')({
  height: `2.45px`,
  width: `2.45px`,
  position: `absolute`,
  left: `7px`,
  top: `15px`,
});

const Path589: any = styled('img')({
  height: `2.45px`,
  width: `2.45px`,
  position: `absolute`,
  left: `2px`,
  top: `15px`,
});

const Path590: any = styled('img')({
  height: `2.45px`,
  width: `2.32px`,
  position: `absolute`,
  left: `5px`,
  top: `4px`,
});

const Path591: any = styled('img')({
  height: `2.45px`,
  width: `2.14px`,
  position: `absolute`,
  left: `0px`,
  top: `11px`,
});

const Completed1: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `28px`,
  textTransform: `none`,
  position: `absolute`,
  left: `1086px`,
  top: `676px`,
});

const Completed2: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `28px`,
  textTransform: `none`,
  position: `absolute`,
  left: `1715px`,
  top: `676px`,
});

const Resend: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `28px`,
  textTransform: `none`,
  position: `absolute`,
  left: `1097px`,
  top: `893px`,
});

const Rectangle512: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `0px 3px 3px rgba(0, 0, 0, 0.16)`,
  borderRadius: `7px`,
  width: `176px`,
  height: `249px`,
  position: `absolute`,
  left: `430px`,
  top: `651px`,
});

const Resend1: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `28px`,
  textTransform: `none`,
  position: `absolute`,
  left: `1727px`,
  top: `893px`,
});

const TemplateSvgrepoCom1: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `31px`,
  height: `26px`,
  left: `452px`,
  top: `727px`,
});

const Rectangle529: any = styled('div')({
  backgroundColor: `rgba(187, 222, 251, 1)`,
  width: `31px`,
  height: `26px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Rectangle530: any = styled('div')({
  backgroundColor: `rgba(63, 81, 181, 1)`,
  width: `23px`,
  height: `4px`,
  position: `absolute`,
  left: `4px`,
  top: `4px`,
});

const Group154: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `23px`,
  height: `12px`,
  left: `4px`,
  top: `11px`,
});

const Rectangle531: any = styled('div')({
  backgroundColor: `rgba(33, 150, 243, 1)`,
  width: `10px`,
  height: `12px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Rectangle532: any = styled('div')({
  backgroundColor: `rgba(33, 150, 243, 1)`,
  width: `10px`,
  height: `12px`,
  position: `absolute`,
  left: `13px`,
  top: `0px`,
});

const ComputerSvgrepoCom1: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `33.6px`,
  height: `29.02px`,
  left: `451px`,
  top: `681px`,
});

const Path633: any = styled('img')({
  height: `22.11px`,
  width: `30.99px`,
  position: `absolute`,
  left: `3px`,
  top: `0px`,
});

const Path634: any = styled('img')({
  height: `22.11px`,
  width: `30.99px`,
  position: `absolute`,
  left: `1px`,
  top: `0px`,
});

const Path635: any = styled('img')({
  height: `19.42px`,
  width: `30.99px`,
  position: `absolute`,
  left: `1px`,
  top: `0px`,
});

const Rectangle513: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  width: `27.04px`,
  height: `15.47px`,
  position: `absolute`,
  left: `3px`,
  top: `2px`,
});

const Group148: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `22.82px`,
  height: `10.09px`,
  left: `5px`,
  top: `4px`,
});

const Rectangle514: any = styled('div')({
  backgroundColor: `rgba(255, 129, 137, 1)`,
  width: `22.82px`,
  height: `2.7px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Rectangle515: any = styled('div')({
  backgroundColor: `rgba(246, 198, 91, 1)`,
  width: `8.3px`,
  height: `5.76px`,
  position: `absolute`,
  left: `0px`,
  top: `4px`,
});

const Rectangle516: any = styled('div')({
  backgroundColor: `rgba(0, 155, 222, 1)`,
  width: `5.78px`,
  height: `1.6px`,
  position: `absolute`,
  left: `10px`,
  top: `5px`,
});

const Rectangle517: any = styled('div')({
  backgroundColor: `rgba(195, 198, 200, 1)`,
  width: `5.78px`,
  height: `1.6px`,
  position: `absolute`,
  left: `17px`,
  top: `5px`,
});

const Rectangle518: any = styled('div')({
  backgroundColor: `rgba(195, 198, 200, 1)`,
  width: `5.78px`,
  height: `1.6px`,
  position: `absolute`,
  left: `10px`,
  top: `8px`,
});

const Rectangle519: any = styled('div')({
  backgroundColor: `rgba(195, 198, 200, 1)`,
  width: `5.78px`,
  height: `1.6px`,
  position: `absolute`,
  left: `17px`,
  top: `8px`,
});

const Group149: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `11.08px`,
  height: `6.32px`,
  left: `13px`,
  top: `22px`,
});

const Path636: any = styled('img')({
  height: `5.34px`,
  width: `8.88px`,
  position: `absolute`,
  left: `1px`,
  top: `0px`,
});

const Path637: any = styled('img')({
  height: `0.98px`,
  width: `7.55px`,
  position: `absolute`,
  left: `0px`,
  top: `5px`,
});

const Path638: any = styled('img')({
  height: `6.32px`,
  width: `4.03px`,
  position: `absolute`,
  left: `7px`,
  top: `0px`,
});

const Ellipse40: any = styled('img')({
  height: `1.48px`,
  width: `1.48px`,
  position: `absolute`,
  left: `16px`,
  top: `20px`,
});

const Group150: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `18.39px`,
  height: `1.16px`,
  left: `0px`,
  top: `28px`,
});

const Rectangle520: any = styled('div')({
  backgroundColor: `rgba(209, 211, 211, 1)`,
  width: `13.03px`,
  height: `1px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Path639: any = styled('img')({
  height: `0.98px`,
  width: `5.36px`,
  position: `absolute`,
  left: `13px`,
  top: `0px`,
});

const Rectangle521: any = styled('div')({
  backgroundColor: `rgba(164, 169, 173, 1)`,
  width: `1.3px`,
  height: `1px`,
  position: `absolute`,
  left: `16px`,
  top: `0px`,
});

const Rectangle522: any = styled('div')({
  backgroundColor: `rgba(164, 169, 173, 1)`,
  width: `1.3px`,
  height: `1px`,
  position: `absolute`,
  left: `14px`,
  top: `0px`,
});

const Rectangle523: any = styled('div')({
  backgroundColor: `rgba(179, 184, 186, 1)`,
  width: `1.3px`,
  height: `1px`,
  position: `absolute`,
  left: `12px`,
  top: `0px`,
});

const Rectangle524: any = styled('div')({
  backgroundColor: `rgba(179, 184, 186, 1)`,
  width: `1.3px`,
  height: `1px`,
  position: `absolute`,
  left: `10px`,
  top: `0px`,
});

const Rectangle525: any = styled('div')({
  backgroundColor: `rgba(179, 184, 186, 1)`,
  width: `1.3px`,
  height: `1px`,
  position: `absolute`,
  left: `8px`,
  top: `0px`,
});

const Rectangle526: any = styled('div')({
  backgroundColor: `rgba(179, 184, 186, 1)`,
  width: `1.3px`,
  height: `1px`,
  position: `absolute`,
  left: `6px`,
  top: `0px`,
});

const Rectangle527: any = styled('div')({
  backgroundColor: `rgba(179, 184, 186, 1)`,
  width: `1.3px`,
  height: `1px`,
  position: `absolute`,
  left: `4px`,
  top: `0px`,
});

const Rectangle528: any = styled('div')({
  backgroundColor: `rgba(179, 184, 186, 1)`,
  width: `1.3px`,
  height: `1px`,
  position: `absolute`,
  left: `2px`,
  top: `0px`,
});

const Group153: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `5.25px`,
  height: `1.15px`,
  left: `23px`,
  top: `28px`,
});

const Group151: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `4px`,
  height: `1.15px`,
  left: `0px`,
  top: `0px`,
});

const Path640: any = styled('img')({
  height: `1.15px`,
  width: `4px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group152: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `3.66px`,
  height: `1.15px`,
  left: `2px`,
  top: `0px`,
});

const Path641: any = styled('img')({
  height: `1.15px`,
  width: `3.66px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const GoogleDriveSocialMed: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `28.5px`,
  height: `25px`,
  left: `454px`,
  top: `773px`,
});

const Path642: any = styled('img')({
  height: `8px`,
  width: `24px`,
  position: `absolute`,
  left: `5px`,
  top: `17px`,
});

const Path643: any = styled('img')({
  height: `25px`,
  width: `13.65px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Path644: any = styled('img')({
  height: `17px`,
  width: `19px`,
  position: `absolute`,
  left: `10px`,
  top: `0px`,
});

const DropboxSvgrepoCom: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `27.21px`,
  height: `26px`,
  left: `454px`,
  top: `819px`,
});

const Path645: any = styled('img')({
  height: `9.52px`,
  width: `12.91px`,
  position: `absolute`,
  left: `0px`,
  top: `10px`,
});

const Path646: any = styled('img')({
  height: `9.52px`,
  width: `12.91px`,
  position: `absolute`,
  left: `14px`,
  top: `10px`,
});

const Path647: any = styled('img')({
  height: `9.52px`,
  width: `12.91px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Path648: any = styled('img')({
  height: `9.52px`,
  width: `12.91px`,
  position: `absolute`,
  left: `14px`,
  top: `0px`,
});

const Path649: any = styled('img')({
  height: `9.74px`,
  width: `16.77px`,
  position: `absolute`,
  left: `5px`,
  top: `16px`,
});

const OnedriveSvgrepoCom: any = styled('img')({
  height: `17.53px`,
  width: `29.6px`,
  position: `absolute`,
  left: `452px`,
  top: `868px`,
});

const Desktop: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(122, 115, 115, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `39px`,
  textTransform: `none`,
  position: `absolute`,
  left: `498px`,
  top: `674px`,
});

const UseTemplate: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(122, 115, 115, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `39px`,
  textTransform: `none`,
  position: `absolute`,
  left: `498px`,
  top: `720px`,
});

const OneDrive: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(122, 115, 115, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `39px`,
  textTransform: `none`,
  position: `absolute`,
  left: `498px`,
  top: `767px`,
});

const DropBox: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(122, 115, 115, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `39px`,
  textTransform: `none`,
  position: `absolute`,
  left: `498px`,
  top: `811px`,
});

const OneDrive1: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(122, 115, 115, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito Sans`,
  fontWeight: `600`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `39px`,
  textTransform: `none`,
  position: `absolute`,
  left: `498px`,
  top: `858px`,
});

const ThreeDotsSvgrepoCom: any = styled('img')({
  height: `5.23px`,
  width: `21.14px`,
  position: `absolute`,
  left: `428px`,
  top: `897px`,
});

const Group158: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `76px`,
  height: `76px`,
  left: `916px`,
  top: `409px`,
});

const Ellipse41: any = styled('img')({
  height: `76px`,
  width: `76px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const DownArrowSvgrepoCom3: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `27.8px`,
  height: `33.75px`,
  left: `24px`,
  top: `20px`,
});

const Path655: any = styled('img')({
  height: `33.75px`,
  width: `27.8px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

function VirtusigDashboard(props: VirtusigDashboardProps): JSX.Element {
  const { fns } = useVirtusigDashboard();

  const [GraphSpring, GraphApi] = useSpring(() => ({
    config: {
      duration: 500,
      easing: easings['easeOutBack'],
    },
    delay: 0,
    from: { transform: 'scale(1)' },
  }));
  return (
    <VirtusigDashboard1>
      <Rectangle387></Rectangle387>
      <VirtusigLogo2
        src={VirtusigLogo2Image}
        loading="lazy"
        alt={'Virtusig logo 2'}
      />
      <Line58></Line58>
      <Rectangle388></Rectangle388>
      <Line59></Line59>
      <Line60></Line60>
      <Line61></Line61>
      <Dashboard>{`Dashboard`}</Dashboard>
      <Manage>{`Manage`}</Manage>
      <Template>{`Template`}</Template>
      <Settings>{`Settings`}</Settings>
      <Frame4>
        <Frame3>
          <ActionRequired className={'colorProperties'}>
            {`Action Required`}
          </ActionRequired>
        </Frame3>
        <Frame2>
          <Q01>{`01`}</Q01>
        </Frame2>
      </Frame4>
      <Q04>{fns.getWaitingForOthers()}</Q04>
      <Q03 fns={fns}>{fns.getCompleted()}</Q03>
      <Q011 fns={fns}>{fns.getExpired()}</Q011>
      <WaitingForOthers>{`Waiting for others`}</WaitingForOthers>
      <Completed>{`Completed`}</Completed>
      <Expired>{`Expired`}</Expired>
      <Rectangle389 fns={fns}></Rectangle389>
      <Rectangle396></Rectangle396>
      <Rectangle397></Rectangle397>
      <FileUpload>{`File Upload`}</FileUpload>
      <QuickStats>{`Quick Stats`}</QuickStats>
      <AverageEnvelopsSent>{`Average Envelops sent`}</AverageEnvelopsSent>
      <RecentActivities>{`Recent Activities`}</RecentActivities>
      <FolderSvgrepoCom>
        <Path556 src={Path556Image} loading="lazy" alt={'Path 556'} />
        <Path557 src={Path557Image} loading="lazy" alt={'Path 557'} />
        <Path558 src={Path558Image} loading="lazy" alt={'Path 558'} />
        <Path559 src={Path559Image} loading="lazy" alt={'Path 559'} />
        <Path560 src={Path560Image} loading="lazy" alt={'Path 560'} />
      </FolderSvgrepoCom>
      <Rectangle390></Rectangle390>
      <Upload>{`Upload`}</Upload>
      <Upload1>{`Max file size 10 MB`}</Upload1>
      <Rectangle392></Rectangle392>
      <Rectangle394></Rectangle394>
      <Rectangle395></Rectangle395>
      <Rectangle393></Rectangle393>
      <Aug23>{`Aug 23`}</Aug23>
      <Aug28>{`Aug 28`}</Aug28>
      <Sept2>{`Sept 2`}</Sept2>
      <Sept7>{`Sept 7`}</Sept7>
      <Sept12>{`Sept 12`}</Sept12>
      <Sept17>{`Sept 17`}</Sept17>
      <Sept22>{`Sept 22`}</Sept22>
      <Sept27>{`Sept 27`}</Sept27>
      <Line31></Line31>
      <Line32></Line32>
      <Q1>{`1`}</Q1>
      <Q2>{`2`}</Q2>
      <Q3>{`3`}</Q3>
      <Q4>{`4`}</Q4>
      <Q5>{`5`}</Q5>
      <Q6>{`6`}</Q6>
      <Q7>{`7`}</Q7>
      <Rectangle398></Rectangle398>
      <Rectangle399></Rectangle399>
      <Rectangle400></Rectangle400>
      <Rectangle401></Rectangle401>
      <Rectangle402></Rectangle402>
      <Rectangle403></Rectangle403>
      <Rectangle404></Rectangle404>
      <Rectangle405></Rectangle405>
      <Rectangle406></Rectangle406>
      <Rectangle407></Rectangle407>
      <Rectangle410></Rectangle410>
      <Rectangle411></Rectangle411>
      <Rectangle413></Rectangle413>
      <Rectangle414></Rectangle414>
      <Rectangle415></Rectangle415>
      <Rectangle416></Rectangle416>
      <Rectangle417></Rectangle417>
      <Rectangle418></Rectangle418>
      <Rectangle412></Rectangle412>
      <Rectangle408></Rectangle408>
      <Rectangle409></Rectangle409>
      <ManikandaRaman>{`Manikanda Raman`}</ManikandaRaman>
      <SentOnDdMmYyyy>{`Sent on: DD/MM/YYYY`}</SentOnDdMmYyyy>
      <SentOnDdMmYyyy1>{`Sent on: DD/MM/YYYY`}</SentOnDdMmYyyy1>
      <SentOnDdMmYyyy2>{`Sent on: DD/MM/YYYY`}</SentOnDdMmYyyy2>
      <SentOnDdMmYyyy3>{`Sent on: DD/MM/YYYY`}</SentOnDdMmYyyy3>
      <RajeshManoharan>{`Rajesh Manoharan`}</RajeshManoharan>
      <VigneshVicky>{`Vignesh Vicky`}</VigneshVicky>
      <AzifAli>{`Azif Ali `}</AzifAli>
      <AvatarSvgrepoCom5>
        <Path308 src={Path308Image} loading="lazy" alt={'Path 308'} />
        <Group12>
          <Group11>
            <Group10>
              <Path194 src={Path194Image} loading="lazy" alt={'Path 194'} />
              <Path195 src={Path195Image} loading="lazy" alt={'Path 195'} />
              <Rectangle31></Rectangle31>
              <Rectangle32></Rectangle32>
              <Path196 src={Path196Image} loading="lazy" alt={'Path 196'} />
              <Path197 src={Path197Image} loading="lazy" alt={'Path 197'} />
              <Path198 src={Path198Image} loading="lazy" alt={'Path 198'} />
              <Path199 src={Path199Image} loading="lazy" alt={'Path 199'} />
              <Path200 src={Path200Image} loading="lazy" alt={'Path 200'} />
            </Group10>
            <Path201 src={Path201Image} loading="lazy" alt={'Path 201'} />
            <Path202 src={Path202Image} loading="lazy" alt={'Path 202'} />
            <Path203 src={Path203Image} loading="lazy" alt={'Path 203'} />
            <Path204 src={Path204Image} loading="lazy" alt={'Path 204'} />
            <Path205 src={Path205Image} loading="lazy" alt={'Path 205'} />
            <Path206 src={Path206Image} loading="lazy" alt={'Path 206'} />
          </Group11>
        </Group12>
      </AvatarSvgrepoCom5>
      <AvatarSvgrepoCom51>
        <Path3081 src={Path3081Image} loading="lazy" alt={'Path 308'} />
        <Group121>
          <Group111>
            <Group101>
              <Path1941 src={Path1941Image} loading="lazy" alt={'Path 194'} />
              <Path1951 src={Path1951Image} loading="lazy" alt={'Path 195'} />
              <Rectangle311></Rectangle311>
              <Rectangle321></Rectangle321>
              <Path1961 src={Path1961Image} loading="lazy" alt={'Path 196'} />
              <Path1971 src={Path1971Image} loading="lazy" alt={'Path 197'} />
              <Path1981 src={Path1981Image} loading="lazy" alt={'Path 198'} />
              <Path1991 src={Path1991Image} loading="lazy" alt={'Path 199'} />
              <Path2001 src={Path2001Image} loading="lazy" alt={'Path 200'} />
            </Group101>
            <Path2011 src={Path2011Image} loading="lazy" alt={'Path 201'} />
            <Path2021 src={Path2021Image} loading="lazy" alt={'Path 202'} />
            <Path2031 src={Path2031Image} loading="lazy" alt={'Path 203'} />
            <Path2041 src={Path2041Image} loading="lazy" alt={'Path 204'} />
            <Path2051 src={Path2051Image} loading="lazy" alt={'Path 205'} />
            <Path2061 src={Path2061Image} loading="lazy" alt={'Path 206'} />
          </Group111>
        </Group121>
      </AvatarSvgrepoCom51>
      <AvatarSvgrepoCom52>
        <Path3082 src={Path3082Image} loading="lazy" alt={'Path 308'} />
        <Group122>
          <Group112>
            <Group102>
              <Path1942 src={Path1942Image} loading="lazy" alt={'Path 194'} />
              <Path1952 src={Path1952Image} loading="lazy" alt={'Path 195'} />
              <Rectangle312></Rectangle312>
              <Rectangle322></Rectangle322>
              <Path1962 src={Path1962Image} loading="lazy" alt={'Path 196'} />
              <Path1972 src={Path1972Image} loading="lazy" alt={'Path 197'} />
              <Path1982 src={Path1982Image} loading="lazy" alt={'Path 198'} />
              <Path1992 src={Path1992Image} loading="lazy" alt={'Path 199'} />
              <Path2002 src={Path2002Image} loading="lazy" alt={'Path 200'} />
            </Group102>
            <Path2012 src={Path2012Image} loading="lazy" alt={'Path 201'} />
            <Path2022 src={Path2022Image} loading="lazy" alt={'Path 202'} />
            <Path2032 src={Path2032Image} loading="lazy" alt={'Path 203'} />
            <Path2042 src={Path2042Image} loading="lazy" alt={'Path 204'} />
            <Path2052 src={Path2052Image} loading="lazy" alt={'Path 205'} />
            <Path2062 src={Path2062Image} loading="lazy" alt={'Path 206'} />
          </Group112>
        </Group122>
      </AvatarSvgrepoCom52>
      <AvatarSvgrepoCom53>
        <Path3083 src={Path3083Image} loading="lazy" alt={'Path 308'} />
        <Group123>
          <Group113>
            <Group103>
              <Path1943 src={Path1943Image} loading="lazy" alt={'Path 194'} />
              <Path1953 src={Path1953Image} loading="lazy" alt={'Path 195'} />
              <Rectangle313></Rectangle313>
              <Rectangle323></Rectangle323>
              <Path1963 src={Path1963Image} loading="lazy" alt={'Path 196'} />
              <Path1973 src={Path1973Image} loading="lazy" alt={'Path 197'} />
              <Path1983 src={Path1983Image} loading="lazy" alt={'Path 198'} />
              <Path1993 src={Path1993Image} loading="lazy" alt={'Path 199'} />
              <Path2003 src={Path2003Image} loading="lazy" alt={'Path 200'} />
            </Group103>
            <Path2013 src={Path2013Image} loading="lazy" alt={'Path 201'} />
            <Path2023 src={Path2023Image} loading="lazy" alt={'Path 202'} />
            <Path2033 src={Path2033Image} loading="lazy" alt={'Path 203'} />
            <Path2043 src={Path2043Image} loading="lazy" alt={'Path 204'} />
            <Path2053 src={Path2053Image} loading="lazy" alt={'Path 205'} />
            <Path2063 src={Path2063Image} loading="lazy" alt={'Path 206'} />
          </Group113>
        </Group123>
      </AvatarSvgrepoCom53>
      <Rectangle419></Rectangle419>
      <Rectangle421></Rectangle421>
      <Rectangle422></Rectangle422>
      <Rectangle420></Rectangle420>
      <Graph
        onMouseOver={() => {
          GraphApi.start({ ...{ transform: 'scale(1.5)' }, delay: 0 });
        }}
        onMouseOut={() => {
          GraphApi.start({ transform: 'scale(1)' });
        }}
        style={{ ...GraphSpring }}
        src={GraphImage}
        loading="lazy"
        alt={'graph'}
      />
      <Line62></Line62>
      <SettingsFill0Wght400
        src={SettingsFill0Wght400Image}
        loading="lazy"
        alt={'settings_FILL0_wght400_GRAD0_opsz48'}
      />
      <NotificationAlarmBel>
        <Path561 src={Path561Image} loading="lazy" alt={'Path 561'} />
        <Path562 src={Path562Image} loading="lazy" alt={'Path 562'} />
      </NotificationAlarmBel>
      <SearchSvgrepoCom7>
        <Group127>
          <Path563 src={Path563Image} loading="lazy" alt={'Path 563'} />
        </Group127>
      </SearchSvgrepoCom7>
      <FlagForUnitedStatesS>
        <Path564 src={Path564Image} loading="lazy" alt={'Path 564'} />
        <Path565 src={Path565Image} loading="lazy" alt={'Path 565'} />
        <Path566 src={Path566Image} loading="lazy" alt={'Path 566'} />
        <Path567 src={Path567Image} loading="lazy" alt={'Path 567'} />
        <Path568 src={Path568Image} loading="lazy" alt={'Path 568'} />
        <Path569 src={Path569Image} loading="lazy" alt={'Path 569'} />
        <Path570 src={Path570Image} loading="lazy" alt={'Path 570'} />
        <Path571 src={Path571Image} loading="lazy" alt={'Path 571'} />
        <Path572 src={Path572Image} loading="lazy" alt={'Path 572'} />
        <Path573 src={Path573Image} loading="lazy" alt={'Path 573'} />
        <Path574 src={Path574Image} loading="lazy" alt={'Path 574'} />
        <Path575 src={Path575Image} loading="lazy" alt={'Path 575'} />
        <Path576 src={Path576Image} loading="lazy" alt={'Path 576'} />
        <Path577 src={Path577Image} loading="lazy" alt={'Path 577'} />
        <Group128>
          <Path578 src={Path578Image} loading="lazy" alt={'Path 578'} />
          <Path579 src={Path579Image} loading="lazy" alt={'Path 579'} />
          <Path580 src={Path580Image} loading="lazy" alt={'Path 580'} />
          <Path581 src={Path581Image} loading="lazy" alt={'Path 581'} />
          <Path582 src={Path582Image} loading="lazy" alt={'Path 582'} />
          <Path583 src={Path583Image} loading="lazy" alt={'Path 583'} />
          <Path584 src={Path584Image} loading="lazy" alt={'Path 584'} />
          <Path585 src={Path585Image} loading="lazy" alt={'Path 585'} />
          <Path586 src={Path586Image} loading="lazy" alt={'Path 586'} />
          <Path587 src={Path587Image} loading="lazy" alt={'Path 587'} />
          <Path588 src={Path588Image} loading="lazy" alt={'Path 588'} />
          <Path589 src={Path589Image} loading="lazy" alt={'Path 589'} />
          <Path590 src={Path590Image} loading="lazy" alt={'Path 590'} />
          <Path591 src={Path591Image} loading="lazy" alt={'Path 591'} />
        </Group128>
      </FlagForUnitedStatesS>
      <Completed1>{`Completed`}</Completed1>
      <Completed2>{`Completed`}</Completed2>
      <Resend>{`Resend`}</Resend>
      <Rectangle512></Rectangle512>
      <Resend1>{`Resend`}</Resend1>
      <TemplateSvgrepoCom1>
        <Rectangle529></Rectangle529>
        <Rectangle530></Rectangle530>
        <Group154>
          <Rectangle531></Rectangle531>
          <Rectangle532></Rectangle532>
        </Group154>
      </TemplateSvgrepoCom1>
      <ComputerSvgrepoCom1>
        <Path633 src={Path633Image} loading="lazy" alt={'Path 633'} />
        <Path634 src={Path634Image} loading="lazy" alt={'Path 634'} />
        <Path635 src={Path635Image} loading="lazy" alt={'Path 635'} />
        <Rectangle513></Rectangle513>
        <Group148>
          <Rectangle514></Rectangle514>
          <Rectangle515></Rectangle515>
          <Rectangle516></Rectangle516>
          <Rectangle517></Rectangle517>
          <Rectangle518></Rectangle518>
          <Rectangle519></Rectangle519>
        </Group148>
        <Group149>
          <Path636 src={Path636Image} loading="lazy" alt={'Path 636'} />
          <Path637 src={Path637Image} loading="lazy" alt={'Path 637'} />
          <Path638 src={Path638Image} loading="lazy" alt={'Path 638'} />
        </Group149>
        <Ellipse40 src={Ellipse40Image} loading="lazy" alt={'Ellipse 40'} />
        <Group150>
          <Rectangle520></Rectangle520>
          <Path639 src={Path639Image} loading="lazy" alt={'Path 639'} />
          <Rectangle521></Rectangle521>
          <Rectangle522></Rectangle522>
          <Rectangle523></Rectangle523>
          <Rectangle524></Rectangle524>
          <Rectangle525></Rectangle525>
          <Rectangle526></Rectangle526>
          <Rectangle527></Rectangle527>
          <Rectangle528></Rectangle528>
        </Group150>
        <Group153>
          <Group151>
            <Path640 src={Path640Image} loading="lazy" alt={'Path 640'} />
          </Group151>
          <Group152>
            <Path641 src={Path641Image} loading="lazy" alt={'Path 641'} />
          </Group152>
        </Group153>
      </ComputerSvgrepoCom1>
      <GoogleDriveSocialMed>
        <Path642 src={Path642Image} loading="lazy" alt={'Path 642'} />
        <Path643 src={Path643Image} loading="lazy" alt={'Path 643'} />
        <Path644 src={Path644Image} loading="lazy" alt={'Path 644'} />
      </GoogleDriveSocialMed>
      <DropboxSvgrepoCom>
        <Path645 src={Path645Image} loading="lazy" alt={'Path 645'} />
        <Path646 src={Path646Image} loading="lazy" alt={'Path 646'} />
        <Path647 src={Path647Image} loading="lazy" alt={'Path 647'} />
        <Path648 src={Path648Image} loading="lazy" alt={'Path 648'} />
        <Path649 src={Path649Image} loading="lazy" alt={'Path 649'} />
      </DropboxSvgrepoCom>
      <OnedriveSvgrepoCom
        src={OnedriveSvgrepoComImage}
        loading="lazy"
        alt={'onedrive-svgrepo-com'}
      />
      <Desktop>{`Desktop`}</Desktop>
      <UseTemplate>{`Use Template`}</UseTemplate>
      <OneDrive>{`One Drive`}</OneDrive>
      <DropBox>{`Drop Box`}</DropBox>
      <OneDrive1>{`One Drive`}</OneDrive1>
      <ThreeDotsSvgrepoCom
        src={ThreeDotsSvgrepoComImage}
        loading="lazy"
        alt={'three-dots-svgrepo-com'}
      />
      <Group158>
        <Ellipse41 src={Ellipse41Image} loading="lazy" alt={'Ellipse 41'} />
        <DownArrowSvgrepoCom3>
          <Path655 src={Path655Image} loading="lazy" alt={'Path 655'} />
        </DownArrowSvgrepoCom3>
      </Group158>
    </VirtusigDashboard1>
  );
}

export default VirtusigDashboard;
