/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Activity from 'src/components/Activity/Activity';
import { ActivityListProps } from 'src/types';
import useActivityList from 'src/components/ActivityList/useActivityList';

const ActivityList1: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
  height: 'auto',
  width: '100%',
});

const ActivityFrame: any = styled('div')({
  display: `grid`,
  position: `relative`,
  isolation: `isolate`,
  padding: `10px`,
  boxSizing: `border-box`,
  height: `auto`,
  margin: `0px`,
  gridTemplateColumns: `repeat(auto-fit, minmax(453.22px, 1fr))`,
  columnGap: `10px`,
  rowGap: `10px`,
  width: `100%`,
});

const Activity1: any = styled(Activity)(({ theme }: any) => ({
  width: `453.22px`,
  height: `191px`,
  margin: `0px`,
}));

function ActivityList(props: ActivityListProps): JSX.Element {
  const { data } = useActivityList(props);

  return (
    <ActivityList1>
      <ActivityFrame>
        {data.activities &&
          data.activities.map((activityX: any, index: number) => {
            return <Activity1 key={index} activity={activityX} />;
          })}
      </ActivityFrame>
    </ActivityList1>
  );
}

export default ActivityList;
