/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import { ActivityListProps } from 'src/types';

const useActivityList = (props: ActivityListProps) => {
  let data: any = {};

  let fns: any = {};
  return { data, fns };
};

export default useActivityList;
