/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import { ActivityListProps } from 'src/types';

const useActivityList = (props: ActivityListProps) => {
  
  const activities = [
    {
      name: "Manikanda Raman",
      activityDate: "Sent on 12/26/2022",
      backgroundColor: "Green",
      status: "Completed"
    },
    {
      name: "Rajesh Manoharan",
      activityDate: "Sent on 12/22/2022",
      backgroundColor: "Green",
      status: "Completed"
    },
    {
      name: "Vignesh Vicky",
      activityDate: "Sent on 12/20/2022",
      backgroundColor: "Purple",
      status: "Resend"
    },
    {
      name: "Azif Ali",
      activityDate: "Sent on 12/10/2022",
      backgroundColor: "Purple",
      status: "Resend"
    }
  ]
  
  let data: any = {activities};

  let fns: any = {};
  return { data, fns };
};

export default useActivityList;
